name: Update Banana Data

on:
  schedule:
    - cron: '0 * * * *'  # co godzinę
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python update_csv.py
        
      - name: Update DEX volume delta
        run: python dex_volume_update.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add banana_data.csv
          git commit -m "Auto-update banana_data.csv"
          git push
